const { app, BrowserWindow, Menu, shell } = require('electron');
const path = require('path');
// Lazily required (not at module top-level) — electron-updater's autoUpdater
// getter calls app.getVersion() as a side effect of being accessed at all,
// which throws if Electron's `app` isn't ready yet. Only ever needed once,
// inside the app.isPackaged branch below.

// Local dev with hot-reload: run `frontend`'s dev server in desktop mode
// (`npm run dev -- --mode desktop`) and point this window at it instead of
// a built file. Toggled by ELECTRON_DEV (set via `npm run dev` in this
// package, see package.json), never set in a packaged build.
const isDev = Boolean(process.env.ELECTRON_DEV);
const DEV_SERVER_URL = 'http://localhost:5173';

function getRendererIndexPath() {
  // Packaged app: frontend/dist-desktop was copied to resources/renderer by
  // electron-builder's extraResources config (see package.json). Running
  // from source (`electron .` in this directory, not via the installer):
  // read the sibling frontend/dist-desktop build directly.
  return app.isPackaged
    ? path.join(process.resourcesPath, 'renderer', 'index.html')
    : path.join(__dirname, '..', '..', 'frontend', 'dist-desktop', 'index.html');
}

function createWindow() {
  const win = new BrowserWindow({
    width: 1360,
    height: 860,
    minWidth: 960,
    minHeight: 640,
    title: 'Izaya EIS — Admin',
    webPreferences: {
      // PHI-adjacent app — renderer never gets Node/filesystem access.
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      preload: path.join(__dirname, 'preload.js'),
    },
  });

  // Open any target="_blank"/window.open link (e.g. "Forgot password" isn't
  // one, but future admin-dashboard links might be) in the OS browser
  // instead of a second Electron window — this is an admin tool, not a
  // browser.
  win.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url);
    return { action: 'deny' };
  });

  if (isDev) {
    win.loadURL(DEV_SERVER_URL);
    win.webContents.openDevTools({ mode: 'detach' });
  } else {
    win.loadFile(getRendererIndexPath());
  }

  return win;
}

// Trim the default Electron menu (File/Edit/View/Window/Help with
// dev-oriented items like "Open DevTools" and irrelevant items like
// "Reload") down to just what makes sense for a packaged admin tool.
function buildMenu() {
  const template = [
    {
      label: 'Izaya EIS',
      submenu: [
        { role: 'about' },
        { type: 'separator' },
        { role: 'quit' },
      ],
    },
    {
      label: 'Edit',
      submenu: [
        { role: 'cut' },
        { role: 'copy' },
        { role: 'paste' },
        { role: 'selectAll' },
      ],
    },
    {
      label: 'Window',
      submenu: [
        { role: 'minimize' },
        { role: 'close' },
      ],
    },
  ];
  Menu.setApplicationMenu(Menu.buildFromTemplate(template));
}

app.whenReady().then(() => {
  buildMenu();
  createWindow();

  // Only meaningful in a packaged build — running unpackaged (`electron .`,
  // whether pointed at the dev server or a local file:// build) has no
  // update metadata (app-update.yml, generated by electron-builder) and
  // would throw.
  if (app.isPackaged) {
    require('electron-updater').autoUpdater.checkForUpdatesAndNotify();
  }

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});
